### ISSUE TITLE
Lightbox Gallery v1.12.0 Evoq 8.4.2 - Modal pop-up not working properly on existing album

### ISSUE THREAD

**Issue by JaySMa** [WillStrohl/dnnextensions#130]
Our live server is running Evoq 7.3.2 and we've updated our development box to Evoq 8.4.2. I just updated Lightbox Gallery to v1.12.0 on our devleopment box.

After upgrade the modal pop-up of the pictures wasn't working properly.  Went into the settings of an existing album and ensured Opacity, Modal, Cyclic and Show Overlay were checked.

Also ensured Show Close Button and Enable Escape Button is checked and updated.

When clicking on a picture, the picure opens in the full windows with a black background.  No close buttons, etc. shown and the only way to move on is to click on the back button.

**Comment by hismightiness** [comment]
Thank you for reporting these issues.  In order for me to help, please report issues in this format:

https://github.com/hismightiness/dnnextensions/wiki/Create-Issues-or-Ideas

**Comment by WillStrohl** [comment]
Unable to duplicate this issue in [the latest release](https://github.com/WillStrohl/dnnextensions/releases/tag/LBGallery-01.15.00).
