### ISSUE TITLE
Lightbox Gallery 01.14.00 dependent on DotNetNuke.Web.Deprecated

### ISSUE THREAD

**Issue by jasclar** [WillStrohl/dnnextensions#190]
Using DNN 09.09.01, and having fully followed the official instructions to remove Telerik (https://dnndocs.com/content/getting-started/setup/telerik-removal/index.html), this also removes DotNetNuke.Web.Deprecated

"Add Album" gives error "DotNetNuke.Services.Exceptions.ModuleLoadException: Could not load file or assembly 'DotNetNuke.Web.Deprecated' or one of its dependencies."

(thank you everyone for working on this !)

**Comment by hismightiness** [comment]
Yes. This and the other modules may need to be reviewed for this update.  Thank you for reporting it.

**Comment by WillStrohl** [comment]
Resolved in [the latest release](https://github.com/WillStrohl/dnnextensions/releases/tag/LBGallery-01.15.00).
