### ISSUE TITLE
Content Injection Module 03.00.00 not saving

### ISSUE THREAD

**Issue by skarpik** [WillStrohl/dnnextensions#208]
DNN 9.10.2 website with 2sxc 13.12.1 LTS installed. Added CI 3.00.00 to a page. Attempted to save JavaScript injection to bottom of page but the submit button does nothing due to an error. Attaching a screenshot of the Console output.

![Screenshot 2022-08-15 011350](https://user-images.githubusercontent.com/3846223/184580318-ab01e4dd-0585-469b-8e66-eeeb987a3bbb.jpg)

**Comment by WillStrohl** [comment]
What is the JavaScript you saved and the settings you used?

**Comment by skarpik** [comment]
Injection Name: GetURLParameter
Priority: 6
Provider: Form Bottom

--------------------------------

function GetURLParameter(sParam)
{
    var sPageURL = window.location.search.substring(1);
    var sURLVariables = sPageURL.split('&');
    for (var i = 0; i < sURLVariables.length; i++) 
    {
        var sParameterName = sURLVariables[i].split('=');
        if (sParameterName[0] == sParam) 
        {
            return sParameterName[1];
        }
    }
}

var kiosk = GetURLParameter('kiosk');

**Comment by WillStrohl** [comment]
You need to wrap the JS in a `<script>` tag just the same as any other HTML. The module is not guessing the kind of HTML you're trying to add to the page.  You can attempt to verify this by inspecting the page output in the browser.

**Comment by skarpik** [comment]
Thank you very much for the solution.
