### ISSUE TITLE
Lightbox Gallery 01.14.00 no longer showing titles under the images

### ISSUE THREAD

**Issue by edisfera** [WillStrohl/dnnextensions#211]
Hi,
after having upgraded from version 01.12.00 to the latest 01.14.00, imge titles disappeared from below the images. Is there a way to have them back?
Thank you

**Comment by WillStrohl** [comment]
Do you have any error messages or anything?  Do you have more details about how the error occurs?  So far, I have no other reports of this, and I'm using it myself still.  :)

**Comment by edisfera** [comment]
Hi Will, thank you for your reply.

There is no error message. You can see the updated page here https://www.italfarmaco.com/it-it/Chi-siamo/Foto-gallery. As you can see, titles are missing below the images (I’m attaching the screen shot of the same site running on my pc with the previous version of the module)… As I said, the only thing I did was to upgrade the module from 1.12.0 to 1.14.0 without changing anything in the setting of the module or of the Albums. I don’t know why the module is failing to generate the following line of html code: <span class="wns_lightbox_title">TITLE OF THE IMAGE</span>

***@***.***


Gaspare Carrani
GENERAL MANAGER,
E-BUSINESS SPECIALIST &
CERTIFIED INFORMATION PRIVACY PROFESSIONAL/EUROPE (CIPP/E)
Edisfera Srl
Via Sistina, 121 - 00187 Roma
Tel. +39 06 62.29.09.20
Cell. +39 334 17.99.835
Fax +39 06 99.29.19.90
www.edisfera.com<http://www.edisfera.com/>
***@***.***<https://www.credential.net/266lfphy?key=52e5b141c373f9b94950adb1b8331a03258226646adb1cd413afabf0ab0a0dcb>
Ai sensi della Legge 196/03 si precisa che le informazioni contenute in questo messaggio sono riservate ed a uso esclusivo del destinatario. Qualora il messaggio in parola Le fosse pervenuto per errore, La preghiamo di eliminarlo senza copiarlo e di non inoltrarlo a terzi, dandocene gentilmente comunicazione. Grazie per la collaborazione.
This message, for the law 196/03, may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this for the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.
EDISFERA s.r.l. -  Via Sistina, 121 - 00187 Roma, Italy - Cap Sociale € 10.000,00 i.v. - C.F. e  P.I. e Iscr. R.I. di Roma IT 08325361007 - REA RM n. 1087831

Da: Will Strohl ***@***.***>
Inviato: mercoledì 16 novembre 2022 01:36
A: WillStrohl/dnnextensions ***@***.***>
Cc: Gaspare Carrani ***@***.***>; Author ***@***.***>
Oggetto: Re: [WillStrohl/dnnextensions] Lightbox Gallery 01.14.00 no longer showing titles under the images (Issue #211)


Do you have any error messages or anything? Do you have more details about how the error occurs? So far, I have no other reports of this, and I'm using it myself still. :)

**Comment by WillStrohl** [comment]
I'm able to reproduce this issue now. I'm not sure when I'll be able to get to the issue to resolve it, but the issue is clear.  Thank you for reporting it.

**Comment by edisfera** [comment]
Thank you Will… when you will release a fix for this issue, I ask you to send me an email so I will upgrade the module.

Thank you for now
Gaspare

Gaspare Carrani
GENERAL MANAGER,
E-BUSINESS SPECIALIST &
CERTIFIED INFORMATION PRIVACY PROFESSIONAL/EUROPE (CIPP/E)
Edisfera Srl
Via Sistina, 121 - 00187 Roma
Tel. +39 06 62.29.09.20
Cell. +39 334 17.99.835
Fax +39 06 99.29.19.90
www.edisfera.com<http://www.edisfera.com/>
***@***.***<https://www.credential.net/266lfphy?key=52e5b141c373f9b94950adb1b8331a03258226646adb1cd413afabf0ab0a0dcb>
Ai sensi della Legge 196/03 si precisa che le informazioni contenute in questo messaggio sono riservate ed a uso esclusivo del destinatario. Qualora il messaggio in parola Le fosse pervenuto per errore, La preghiamo di eliminarlo senza copiarlo e di non inoltrarlo a terzi, dandocene gentilmente comunicazione. Grazie per la collaborazione.
This message, for the law 196/03, may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this for the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.
EDISFERA s.r.l. -  Via Sistina, 121 - 00187 Roma, Italy - Cap Sociale € 10.000,00 i.v. - C.F. e  P.I. e Iscr. R.I. di Roma IT 08325361007 - REA RM n. 1087831

Da: Will Strohl ***@***.***>
Inviato: giovedì 24 novembre 2022 02:51
A: WillStrohl/dnnextensions ***@***.***>
Cc: Gaspare Carrani ***@***.***>; Author ***@***.***>
Oggetto: Re: [WillStrohl/dnnextensions] Lightbox Gallery 01.14.00 no longer showing titles under the images (Issue #211)


I'm able to reproduce this issue now. I'm not sure when I'll be able to get to the issue to resolve it, but the issue is clear. Thank you for reporting it.

**Comment by WillStrohl** [comment]
I've triaged this issue, but I'm not sure how soon I can get to it right now.
